### PR TITLE
[versions.list] Add full file

### PR DESCRIPTION
**Pull request by segiddins**
\c @fotanus @indirect

### CODE REVIEW

**Comment by indirect** [comment]
didn't want to merge this after all?

**Comment by segiddins** [comment]
Nah, I'm regenerating info checksums right now, but it's taking literally tens of hours :cry:

**Comment by fotanus** [comment]
:-( do you think sequel queue the inserts to avoid switching the context too much between the application and the database?

**Comment by segiddins** [comment]
No clue, it's just only doing like 2-3 a second, which is really slow.

**Comment by fotanus** [comment]
You can try to use the method `update_sql` instead of `update` and concatenate a lot of inserts (lets say, 1k) and execute only once. This should speedup a lot, because what takes most time is switching between the app and database context. It helped me on the past.

**Pull request closed without merging**
