### PR TITLE
New index format

### PR DESCRIPTION
**Pull request by fotanus**
This is a `merge master`, with conflicts resolved.

### CODE REVIEW

**Comment by indirect** [comment]
@fotanus looks like you need to make rubocop happy now that you have merged in master. :)

**Comment by fotanus** [comment]
@indirect hopefully it will not arrest me :-)

**Comment by indirect** [comment]
@homu r+

**Comment by segiddins** [comment]
Any reason we're merging instead of rebasing?

**Comment by fotanus** [comment]
This should't be merged yet because it needs the rubocop changes too. I can send next one as rebase if you like best, but then I think it will be harder to find merging problems on staging. But maybe I'm wrong?

**Comment by indirect** [comment]
@fotanus maybe just merge master in to this PR again for now?

**Comment by indirect** [comment]
@segiddins I think the plan was to get the tests green, shake it down on staging, and then rebase and squash as necessary before merging in to master?

**Comment by segiddins** [comment]
ok sounds good!

**Comment by fotanus** [comment]
One more heads up on this: I changed  alot of code because rubocop told me to do so. If we are keeping the bundler/bundler rubocop configs, It is better to avoid those changes on this merge. So I would consider merge #103 first, then I merge it again discarding all the stuff I changed that should't actually be (like changes because of method complexity and stuff), or branch #103 and merge the master. Thoughts?

**Comment by segiddins** [comment]
@fotanus #103 has already been merged

**Comment by fotanus** [comment]
:O Thanks!

**Comment by indirect** [comment]
Okay, this is close! We need green tests, and we need to finish the checklist in #77, and then we are good to go.

**Comment by indirect** [comment]
I'm going to merge this, since it updates the `new_index_format` branch in this repo. Let's keep working on #77, pushing to bundler/bundler-api#new_index_format, until the checklist is finished!

**Comment by fotanus** [comment]
Sorry for the late notice, Im in a trip without a computer this weekend.  That is why i pushed something with a typo. If you have questions I can help thoug my gmail, just sent there. @segiddins @indirect

**Pull request merged**
