### PR TITLE
Update to Ruby 2.2.3

### PR DESCRIPTION
**Pull request by segiddins**

### CODE REVIEW

**Comment by indirect** [comment]
@homu r+

**Comment by barosl** [comment]
Hi! Sorry for off-topic, but I just found that this PR has stalled in the Homu queue for some time. I was worried if this is due to a bug in Homu, but I now realized the reason is that the recent change (6d6e06d) made Travis build only the `master` branch, but for Homu to work, the `auto` branch should also have been enabled. Is this intentional? Or is this a temporal breakage that soon will be resolved?

**Comment by segiddins** [comment]
Oops, that's my bad!

**Comment by indirect** [comment]
@homu r+

**Comment by indirect** [comment]
@barosl We did this once before on Bundler, too... thanks for figuring it out!

**Comment by barosl** [comment]
Great! :+1:

Also note that, technically speaking, building the `master` branch is *not* necessary, because the commit tested on the `auto` branch is exactly the same as the one merged later into `master`. So configuring Travis to build only the `auto` branch would be enough, and probably be the most efficient.

However I've yet to decide if this approach should be endorsed or not. Not building the `master` branch will make the build badge outdated, so I'm not exactly sure if going without a badge is worth it. What do you think of this?

**Comment by segiddins** [comment]
On bundler, we build master, auto, stable, and dev.

**Comment by indirect** [comment]
@barosl it's definitely hard to balance builds. I mostly wish that Travis knew the sha was the same and didn't test it again, and just showed the previous build for that sha. I also wish that Homu linked directly to the Travis build from the comment and PR status notification. :) 

We've tried not building PRs automatically and waiting for r+, and that slowed down feedback to the PR author too much. Ultimately, I think my ideal system would be Travis automatically testing the merge commit when PRs are opened, and Homu simply using that test result if the base has not been updated before r+. If the base is updated but merge is still possible, Homu would build the new merge commit on r+.

That way Travis PR builds and Homu builds would work together (today they are 100% separate), PR authors would get feedback right away, r+ would cause an immediate merge if the base was still the same, and Homu could build new merge commits if needed for r+ PRs as it already does today.

Maybe I should move this to a Homu ticket? :)

**Comment by barosl** [comment]
@indirect

> I mostly wish that Travis knew the sha was the same and didn't test it again

Yeah, I want that too, because currently Travis just tests the same commit over and over, even within the same branch... I've been thinking of fixing this issue for a long time, and it seems to require either of:

- Homu uses the `tmp` branch to prepare a merge commit, and the user explicitly sets the branch as not built, or
- Let Homu use a local Git command, manipulating the repository locally and preparing the merge commit.

The first method is quite bothersome to the users, and needs extra promotion to be used widely. The second method will consume a fair amount of storage of the Homu server, and also will slow down various Git operations a bit. Both have cons, but nowadays I'm more leaning towards the latter.

> Homu simply using that test result if the base has not been updated before r+.

Wow, that sounds like a fascinating idea! It seems to be a pretty neat trick. Yeah, please file a ticket! I will test this approach soon.

**Pull request merged**
