### PR TITLE
rubygems mirror support

### PR DESCRIPTION
**Pull request by qhwa**
This commit add support of usage for a rubygems mirror.
For a rubygems mirror site, one can fetch specs marshal from local server after synchronization of gems.

### CODE REVIEW

**Comment by segiddins** [comment]
I'm good to merge this if it gets rebased, @andremedeiros / @indirect ?

**Comment by indirect** [comment]
Yeah, this looks good to me.

**Comment by qhwa** [comment]
Thanks @indirect @segiddins @homu 
:beers:

**Comment by segiddins** [comment]
@qhwa could you just rebase this, please?

**Comment by giracc** [comment]
@segiddins I see @homu has already [done the same thing](https://github.com/bundler/bundler-api/commit/2fa2e64996ef02a7fdf92bbcb1bc0674d52a8ddf), so this PR can be closed without merging.

**Comment by qhwa** [comment]
@segiddins , I see @homu has already [done the same commits](https://github.com/bundler/bundler-api/commit/2fa2e64996ef02a7fdf92bbcb1bc0674d52a8ddf) but with better codes.

We can close this PR without merging it.

**Comment by segiddins** [comment]
ah @indirect did it manually without linking back to this PR.

**Pull request closed without merging**
