### PR TITLE
Cache dependencies

### PR DESCRIPTION
**Pull request by arthurnn**
The idea here is to speed-up the `/dependencies` API. And avoid timeouts on the server workers.

### Problem
`api/v1/dependencies?gems=huge_list` can take a while as this needs to return all dependencies for the list of gems given. The sql query is the bigger bottom neck https://github.com/bundler/bundler-api/blob/master/lib/bundler_api/dep_calc.rb#L8-L21, besides that, to Marshal a big list is not fast too.

### Solution
Cache the dependencies if only one gem given.

### Work necessary on the bundler client
https://github.com/bundler/bundler/blob/master/lib/bundler/fetcher.rb#L326 needs to be a `each` instead, so it will request only one gem.
Old version of clients will still work, as the API will still support batched fetches.

#### Simple benchmark I did locally

BEFORE (batch request dependencies by 50 gems):
```
Fetching gem metadata from http://localhost:5000/.......It took 3680.437 milliseconds
Fetching version metadata from http://localhost:5000/...It took 2091.268 milliseconds
Fetching dependency metadata from http://localhost:5000/..It took 2.7009999999999996 milliseconds (edited)
```

AFTER (separate requests dependencies to 1 gem per request):
```
Fetching gem metadata from http://localhost:5000/.......It took 1437.915 milliseconds
Fetching version metadata from http://localhost:5000/...It took 1117.9479999999999 milliseconds
Fetching dependency metadata from http://localhost:5000/..It took 3.666 milliseconds
```

review @andremedeiros @hone @indirect @dwradcliffe

### CODE REVIEW

**Comment by arthurnn** [comment]
I will add regression tests for this, just dont merge it yet. But would like to get feedback.

**Comment by indirect** [comment]
if we change the client to only request one gem at a time, we should make sure pipelining works to prevent many http requests, which would slow down high latency connections a huge amount.

**Comment by arthurnn** [comment]
@indirect good point, as far as I can tell everything should work. Our fetcher uses ` Net::HTTP::Persistent` https://github.com/bundler/bundler/blob/master/lib/bundler/fetcher.rb#L122 , and the server dont force close the connection, and as far as I can tell puma works with keep-alive.

**Comment by indirect** [comment]
Keepalive is good, but that's not what I'm talking about... even with keepalive, one round trip to the server per gem is completely unusable from, say, South Africa. It's 2-4 _seconds_ per round trip. What we need is Pipelining, where many requests are all made at once over the same connection, and the responses are handled as they come back.

**Comment by TimMoore** [comment]
Once the client changes are done, I'm happy to do some testing from the Antipodes.

Looks like ICMP is disabled on api.rubygems.org so I can't check ping time, but IIRC it's around 350ms from here.

The overhead for a single API request is pretty slow:

```
$ time curl -IHEAD 'https://api.rubygems.org/api/v1/dependencies?gems=bundler'
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 26 Feb 2015 21:51:32 GMT
Content-Type: application/octet-stream
Content-Length: 8817
Connection: keep-alive
X-Content-Type-Options: nosniff
Vary: Accept-Encoding
Via: 1.1 vegur


real	0m1.765s
user	0m0.032s
sys	0m0.009s
```

**Comment by arthurnn** [comment]
After talking to @indirect , we decided the cache should be on CDN layer and not on memcached. so I opened #60.

**Pull request closed without merging**
