### PR TITLE
Rework error handling for more information and less log spam

### PR DESCRIPTION
**Pull request by indirect**

### CODE REVIEW

**Comment by indirect** [comment]
cc @segiddins

**Comment by segiddins** [comment]
What's the advantage of dumping appsignal?

**Comment by indirect** [comment]
@segiddins we're not getting anything useful from it? afaik, no one is ever looking at errors or metrics in Appsignal. Also no one is maintaining the integration, so the ancient version of the appsignal gem is dumping thread-related warnings into the logs continuously.

If we log application errors to Papertrail and alert them into Slack, at least then we have a single place to see errors from the app, from background jobs, and from Heroku itself.

**Comment by segiddins** [comment]
👍🏻 as long as we get the same immediate slack messages we get now

**Comment by indirect** [comment]
I have already set up the papertrail to slack connection that will report errors as they arrive in the logs 👍

**Comment by segiddins** [comment]
@homu r+

**Pull request merged**
