### PR TITLE
Fix redirection strategy, symbol instead of the actual id

### PR DESCRIPTION
**Pull request by pcarranza**
@indirect This is a fix for a bug that is in mainline.

A fix of 2 lines that are plain wrong, my bad.

### CODE REVIEW

**Comment by segiddins** [comment]
👍🏻, but do we not have tests covering this?

**Comment by pcarranza** [comment]
We do, but we don't check the url at all: https://github.com/bundler/bundler-api/blob/master/spec/web_spec.rb#L180-L186

**Comment by segiddins** [comment]
In that case, tests to prevent this regressing would be ace

**Comment by pcarranza** [comment]
ACK, will do :smile:

**Comment by pcarranza** [comment]
Done

Previous version was failing like this:
```
Failure/Error: expect(last_response.location).to end_with("/gems/rack")
expected "https://www.rubygems.org/gems/id" to end with "/gems/rack"
```

With the added expectations tests just pass and capture the case.

**Comment by segiddins** [comment]
Awesome!
@homu r+

**Pull request merged**
