### PR TITLE
Revert the Reverts

### PR DESCRIPTION
**Pull request by segiddins**
@indirect @arthurnn @dwradcliffe

### CODE REVIEW

**Comment by indirect** [comment]
We just plain don't want a retry with sleep 30, I don't think. The Fastly cache expiration seems good. 👍

**Comment by segiddins** [comment]
@indirect iirc @RochesterinNYC added that for the sake of the rake tasks?

**Comment by RochesterinNYC** [comment]
@segiddins Haven't contributed to bundler-api yet. Think you're referring to @allenzhao and #130 perhaps?

**Comment by segiddins** [comment]
Ah yes I was, my bad.

**Comment by segiddins** [comment]
Backed out the retry revert, now it's only the fastly perge commit.

**Comment by arthurnn** [comment]
have the performance on this changed? because this was causing the perf regression.

**Comment by segiddins** [comment]
I thought this _wasnt_ what was causing the regressions? Didn't we still have problems after reverting this?

**Comment by arthurnn** [comment]
no, as far as I remember, after reverting the purges on fastly, it fixed the regression.

**Comment by arthurnn** [comment]
https://github.com/bundler/bundler-api/commit/111186fda1fd51ff315c351cdf430b272ffc5913 was the one

**Comment by segiddins** [comment]
Well, the new index is _broken_ without this commit in it. Would doing the purges in a separate thread help?

**Comment by arthurnn** [comment]
> Well, the new index is broken without this commit in it. Would doing the purges in a separate thread help?

I dunno tbh, i think the problem is indeed the purges been too slow in the request thread.
Not sure if it will make it better to have them in a separate thread. Maybe yes, as IO has no GIL.

**Comment by segiddins** [comment]
@arthurnn it'll also mean the threads that handle requests are still free to accept new requests

**Comment by allenzhao** [comment]
I just saw this, and I'm not following a little bit...
Anything I can do to help? ;)

**Comment by indirect** [comment]
@allenzhao I think we just need to move `@cache.purge_specs; @cache.purge_gem` into a background thread, so that the response isn't blocked. Wrapping that code inside the thread so that we report exceptions to... wherever it is that we report exceptions to... (papertrail? I don't remember 😬 ) would also be great.

**Comment by segiddins** [comment]
@indirect @arthurnn look better?

**Comment by indirect** [comment]
I'm worried that exceptions in those threads will be silently eaten, and never reported anywhere—I think we need to explicitly rescue and dispatch to whatever our exception-reporting setup is.

**Comment by indirect** [comment]
@homu r+

**Comment by segiddins** [comment]
This is now passing

**Comment by segiddins** [comment]
r?

**Comment by indirect** [comment]
👍 

@homu r+

**Pull request merged**
