### PR TITLE
Remove puma worker killer

### PR DESCRIPTION
**Pull request by indirect**

### CODE REVIEW

**Comment by dwradcliffe** [comment]
:+1:

**Comment by indirect** [comment]
@homu r+

**Comment by segiddins** [comment]
I thought this was helping keep leaks under control?

**Comment by indirect** [comment]
@segiddins we halved the number of puma processes on each dyno and doubled the number of dynos—I'm not completely positive whether we had a leak or too many workers per dyno. This will let us figure that out, and also fix the failed requests that happen every time a worker is killed.

**Pull request merged**
