### PR TITLE
Separate yanked_info_checksum for yanked versions

### PR DESCRIPTION
**Pull request by segiddins**
\c @indirect @sonalkr132

### CODE REVIEW

**Comment by sonalkr132** [comment]
I understand the need to update `info checksum` when a version is yanked but why do need a separate new column(`yanked_info_checksum`) for it? Why not update existing [`info_checksum`](https://github.com/bundler/bundler-api/blob/master/db/migrations/08_add_info_checksum_to_versions.rb)?

Also, it could use a test case [here](https://github.com/bundler/bundler-api/blob/master/spec/web_spec.rb#L156):
```Ruby
context "POST /api/v1/remove_spec.json" do
  ...
  it "updates the info checksum in the database" do
  ...
  end
end
```

**Comment by segiddins** [comment]
Updating the existing checksum would break the versions file for the original line for the version that has been yanked. RubyGems.org will require the same kind of change.

**Comment by indirect** [comment]
This looks right to me--the line in versions when a gem is added will definitely have a different info checksum than the line to versions when that gem is yanked.

@sonalkr132 because the versions file is append-only (to make it easy to cache and update on users machines) we can't change the original info checksum. changing any data that has been used to build the versions file changes the entire file, and everyone would have to download it again from scratch.

**Comment by indirect** [comment]
@homu r+

**Pull request merged**
