### PR TITLE
Cache dependencies 2

### PR DESCRIPTION
**Pull request by arthurnn**
Better then #59 and #60.

### Problem
`api/v1/dependencies?gems=huge_list` can take a while as this needs to return all dependencies for the list of gems given. The sql query is the bigger bottom neck https://github.com/bundler/bundler-api/blob/master/lib/bundler_api/dep_calc.rb#L8-L21, besides that, to Marshal a big list is not fast too.

### Solution 
After we realized that fastly cannot handle http-pipelining, we ditched the idea of caching on CDN layer.
Back to memcache. After talking to @evanphx , he told me that puma can handle http-pipelining, however it does not parallelize the requests, and process them in the same worker in serial. If all requests will be processed by the same worker, and we cannot CDN cache, we can keep the same API, but internally cache the query result in memcached, and always try to `get_multi` them before. So we fallback only the gems that are not in the cache, and not everything.

### Client changes
The good thing about this solution, is that the client wont have to change at all.

### Benchmarks
Before cache:
```
Fetching gem metadata from http://localhost:9292/.......It took 9777.741 milliseconds
Fetching version metadata from http://localhost:9292/...It took 821.523 milliseconds
Fetching dependency metadata from http://localhost:9292/..It took 2.2369999999999997 milliseconds
```

After cache:
```
Fetching gem metadata from http://localhost:9292/.......It took 963.947 milliseconds
Fetching version metadata from http://localhost:9292/...It took 804.099 milliseconds
Fetching dependency metadata from http://localhost:9292/..It took 2.2009999999999996 milliseconds
```

review @andremedeiros @hone @indirect @dwradcliffe

### CODE REVIEW

**Comment by evanphx** [comment]
:+1: This is an easy change and is unlikely to cause issues. It might relieve a lot of the load on the DB, which is what we need to find out. That relieved load should result in fewer timeouts. We won't know until we try.

**Comment by dwradcliffe** [comment]
Should we deploy to a new heroku app just to verify memcache config and that we return valid results?

**Comment by indirect** [comment]
We can deploy to the staging Heroku app to test things out first.

**Comment by arthurnn** [comment]
Tested this on staging and it works fine. Checked memcached there, and it is filling it, and did a few benchmarks that showed to be about 5x faster.

**Comment by olivierlacan** [comment]
Thanks @arthurnn! :heart:

**Comment by dwradcliffe** [comment]
Looking really good:

response time

**Comment by sferik** [comment]
Amazing!

**Comment by joaomdmoura** [comment]
:+1:  Great work @arthurnn

**Comment by hone** [comment]
thanks @arthurnn !

**Comment by indirect** [comment]
making a note here, huge success :D

**Comment by larrylv** [comment]
Thanks @arthurnn :heart:

**Pull request merged**
